remote_theme: chrisrhymes/bulma-clean-theme
timezone: Asia/Seoul

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default"
      hide_hero: true
