title: "Progress:"
tagline: KES185
remote_theme: chrisrhymes/bulma-clean-theme
email: eunsukim@yonsei.ac.kr
url: "https://kes185.github.io"
#baseurl: "/bulma-clean-theme"

permalink: pretty

plugins:
  - github-pages
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - kramdown
  - rouge

include: 
  - _pages
  
exclude: 



livereload: true
sass:
  style: compressed
  source_dir: _sass
paginate: 5
paginate_path: "/blog/page:num"
category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default"
      author: "kes185"
      hide_hero: true
      show_sidebar: false
      #menubar: example_menu
      hide_footer: true
  -
    scope:
      path: ""
      type: "pages"
    values:
      show_sidebar: false
      #menubar: example_menu
      hide_footer: true
  -
    scope:
      path: ""
      type: "posts"
    values:
      author: "kes185"
      layout: post
      show_sidebar: false
      menubar: example_menu
      hide_footer: true
      
markdown: kramdown
highlighter: rouge
